import { randomBytes } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

import { parse as parseDotenv } from 'dotenv';

const ENV_ORDER = [
  'NODE_ENV',
  'HOST',
  'PORT',
  'PUBLIC_BASE_URL',
  'MCP_PATH',
  'REST_BASE_PATH',
  'OPENAPI_PATH',
  'ALLOWED_HOSTS',
  'MONGO_URL',
  'MONGO_DB',
  'MONGO_SERVER_SELECTION_TIMEOUT_MS',
  'TELEGRAM_MODE',
  'TELEGRAM_API_ID',
  'TELEGRAM_API_HASH',
  'TELEGRAM_SESSION_FILE',
  'TELEGRAM_SYNC_LIMIT',
  'TELEGRAM_SYNC_ENABLED',
  'TELEGRAM_SYNC_INTERVAL_SECONDS',
  'TELEGRAM_SYNC_ON_START',
  'OPENAI_API_KEY',
  'OPENAI_TRANSCRIPTION_ENABLED',
  'OPENAI_TRANSCRIPTION_MODEL',
  'OPENAI_TRANSCRIPTION_RESPONSE_FORMAT',
  'OPENAI_TRANSCRIPTION_PROMPT',
  'OPENAI_TRANSCRIPTION_LANGUAGE',
  'OPENAI_TRANSCRIPTION_CHUNKING_STRATEGY',
  'AUDIO_TRANSCRIPTION_SOURCE_IDS',
  'AUDIO_TRANSCRIPTION_SOURCE_TAGS',
  'AUDIO_TRANSCRIPTION_INTERVAL_SECONDS',
  'AUDIO_TRANSCRIPTION_ON_START',
  'AUDIO_TRANSCRIPTION_BATCH_SIZE',
  'AUDIO_TRANSCRIPTION_LOCK_MS',
  'AUDIO_TRANSCRIPTION_MAX_ATTEMPTS',
  'AUDIO_TRANSCRIPTION_WORK_DIR',
  'AUDIO_TRANSCRIPTION_MAX_FILE_BYTES',
  'AUDIO_TRANSCRIPTION_SPLIT_LARGE_FILES',
  'FFMPEG_PATH',
  'TELEGRAM_BOT_ENABLED',
  'TELEGRAM_BOT_TOKEN',
  'TELEGRAM_BOT_ALLOWED_CHAT_IDS',
  'TELEGRAM_BOT_TIMEZONE',
  'ALLOWED_SOURCE_IDS',
  'APP_AUTH_TOKEN',
  'ALLOW_UNAUTHENTICATED'
];

const PROTECTED_KEYS = new Set([
  'TELEGRAM_API_ID',
  'TELEGRAM_API_HASH',
  'OPENAI_API_KEY',
  'TELEGRAM_BOT_TOKEN',
  'APP_AUTH_TOKEN'
]);

function defaultEnv({ production = false, tokenFactory = generateAuthToken } = {}) {
  return {
    NODE_ENV: production ? 'production' : 'development',
    HOST: '127.0.0.1',
    PORT: '3010',
    PUBLIC_BASE_URL: 'https://celticspear.com',
    MCP_PATH: '/mcp',
    REST_BASE_PATH: '/tg-mcp/api',
    OPENAPI_PATH: '/tg-mcp/openapi.json',
    ALLOWED_HOSTS: '127.0.0.1,localhost,celticspear.com,www.celticspear.com',
    MONGO_URL: 'mongodb://127.0.0.1:27017',
    MONGO_DB: 'tg_mcp',
    MONGO_SERVER_SELECTION_TIMEOUT_MS: '5000',
    TELEGRAM_MODE: 'user',
    TELEGRAM_API_ID: '',
    TELEGRAM_API_HASH: '',
    TELEGRAM_SESSION_FILE: production ? '/srv/tg-mcp/shared/sessions/telegram.session' : './sessions/telegram.session',
    TELEGRAM_SYNC_LIMIT: '200',
    TELEGRAM_SYNC_ENABLED: 'false',
    TELEGRAM_SYNC_INTERVAL_SECONDS: '300',
    TELEGRAM_SYNC_ON_START: 'true',
    OPENAI_API_KEY: '',
    OPENAI_TRANSCRIPTION_ENABLED: 'false',
    OPENAI_TRANSCRIPTION_MODEL: 'gpt-4o-transcribe',
    OPENAI_TRANSCRIPTION_RESPONSE_FORMAT: 'json',
    OPENAI_TRANSCRIPTION_PROMPT: '',
    OPENAI_TRANSCRIPTION_LANGUAGE: '',
    OPENAI_TRANSCRIPTION_CHUNKING_STRATEGY: '',
    AUDIO_TRANSCRIPTION_SOURCE_IDS: '',
    AUDIO_TRANSCRIPTION_SOURCE_TAGS: '',
    AUDIO_TRANSCRIPTION_INTERVAL_SECONDS: '3600',
    AUDIO_TRANSCRIPTION_ON_START: 'true',
    AUDIO_TRANSCRIPTION_BATCH_SIZE: '1',
    AUDIO_TRANSCRIPTION_LOCK_MS: '600000',
    AUDIO_TRANSCRIPTION_MAX_ATTEMPTS: '3',
    AUDIO_TRANSCRIPTION_WORK_DIR: production ? '/srv/tg-mcp/shared/audio-work' : './tmp/audio-transcriptions',
    AUDIO_TRANSCRIPTION_MAX_FILE_BYTES: String(25 * 1024 * 1024),
    AUDIO_TRANSCRIPTION_SPLIT_LARGE_FILES: 'true',
    FFMPEG_PATH: 'ffmpeg',
    TELEGRAM_BOT_ENABLED: 'false',
    TELEGRAM_BOT_TOKEN: '',
    TELEGRAM_BOT_ALLOWED_CHAT_IDS: '',
    TELEGRAM_BOT_TIMEZONE: 'Europe/Chisinau',
    ALLOWED_SOURCE_IDS: '',
    APP_AUTH_TOKEN: tokenFactory(),
    ALLOW_UNAUTHENTICATED: 'false'
  };
}

function generateAuthToken() {
  return randomBytes(32).toString('base64url');
}

async function readExistingEnv(envFile) {
  try {
    const text = await fs.readFile(envFile, 'utf8');
    return {
      existed: true,
      text,
      values: parseDotenv(text)
    };
  } catch (caught) {
    if (caught.code === 'ENOENT') {
      return {
        existed: false,
        text: '',
        values: {}
      };
    }
    throw caught;
  }
}

function envLineValue(value) {
  const text = String(value ?? '');
  if (/^[A-Za-z0-9_./:@,+-]*$/.test(text)) {
    return text;
  }
  return JSON.stringify(text);
}

function renderEnv(values) {
  const known = ENV_ORDER
    .map((key) => `${key}=${envLineValue(values[key] ?? '')}`)
    .join('\n');
  const extraKeys = Object.keys(values)
    .filter((key) => !ENV_ORDER.includes(key))
    .sort();
  const extras = extraKeys
    .map((key) => `${key}=${envLineValue(values[key])}`)
    .join('\n');

  return [
    '# Generated by tg-mcp setup-env. Keep this file private.',
    known,
    extras
  ]
    .filter(Boolean)
    .join('\n\n')
    .concat('\n');
}

function timestamp(date = new Date()) {
  return date.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z');
}

export async function setupEnvFile({
  envFile = '.env',
  production = false,
  force = false,
  values = {},
  tokenFactory = generateAuthToken,
  now = new Date()
} = {}) {
  const resolved = path.resolve(envFile);
  const existing = await readExistingEnv(resolved);
  const defaults = defaultEnv({ production, tokenFactory });
  const explicitValues = Object.fromEntries(
    Object.entries(values).map(([key, value]) => [key, String(value)])
  );
  const next = { ...existing.values };
  const writtenKeys = [];
  const generatedKeys = [];
  const preservedKeys = [];
  const updatedKeys = [];

  for (const key of ENV_ORDER) {
    const hasExplicit = Object.hasOwn(explicitValues, key);
    const existingValue = existing.values[key];
    const existingHasValue = existingValue !== undefined && existingValue !== '';

    if (hasExplicit) {
      next[key] = explicitValues[key];
      writtenKeys.push(key);
      if (existing.existed && existingValue !== explicitValues[key]) {
        updatedKeys.push(key);
      }
      continue;
    }

    if (PROTECTED_KEYS.has(key) && existingHasValue) {
      next[key] = existingValue;
      preservedKeys.push(key);
      continue;
    }

    if (existingHasValue && !force) {
      next[key] = existingValue;
      preservedKeys.push(key);
      continue;
    }

    next[key] = defaults[key] ?? '';
    writtenKeys.push(key);
    if (key === 'APP_AUTH_TOKEN' && !existingHasValue) {
      generatedKeys.push(key);
    }
    if (existing.existed && existingValue !== next[key]) {
      updatedKeys.push(key);
    }
  }

  for (const [key, value] of Object.entries(explicitValues)) {
    if (!ENV_ORDER.includes(key)) {
      next[key] = value;
      writtenKeys.push(key);
      if (existing.values[key] !== value) {
        updatedKeys.push(key);
      }
    }
  }

  await fs.mkdir(path.dirname(resolved), { recursive: true });

  let backupFile = null;
  if (existing.existed) {
    backupFile = `${resolved}.before-setup-${timestamp(now)}`;
    await fs.copyFile(resolved, backupFile);
  }

  const tempFile = `${resolved}.tmp-${process.pid}`;
  await fs.writeFile(tempFile, renderEnv(next), { mode: 0o600 });
  await fs.rename(tempFile, resolved);
  await fs.chmod(resolved, 0o600);

  return {
    envFile: resolved,
    existed: existing.existed,
    backupFile,
    writtenKeys: [...new Set(writtenKeys)].sort(),
    generatedKeys: [...new Set(generatedKeys)].sort(),
    updatedKeys: [...new Set(updatedKeys)].sort(),
    preservedKeys: [...new Set(preservedKeys)].sort()
  };
}
